language: go

env:
  matrix:
  - GO111MODULE=on

go:
  - 1.18.x

before_install:
  - go get -t -v ./...

install:
  - make tools

script: make travis

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
